=== dmitry300/DmitryGarist/task08/src/main/resources/data/medicine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/bean"
        xmlns:tns="http://www.training.by/bean"
        elementFormDefault="qualified">

    <element name="entity" type="tns:Entity" abstract="true"></element>
    <element name="medicine" type="tns:Medicine" substitutionGroup="tns:entity"></element>

    <element name="medicines">
        <complexType>
            <sequence>
                <element ref="tns:entity"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Entity">
        <sequence>
            <element name="name" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Medicine">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="pharm" type="string"/>
                    <element name="group" type="tns:Group"/>
                    <element name="analogs">
                        <complexType>
                            <sequence>
                                <element name="analog" type="string" maxOccurs="unbounded"/>
                            </sequence>
                        </complexType>
                    </element>
                    <element name="version" type="string"/>
                    <element name="certificate" type="tns:Certificate"/>
                    <element name="package" type="tns:Package"/>
                    <element name="dosage" type="tns:Dosage"/>
                </sequence>
                <attribute name="id" type="int" use="required"/>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Dosage">
        <sequence>
            <element name="dose" type="string"/>
            <element name="frequency" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Package">
        <sequence>
            <element name="type" type="string"/>
            <element name="amount" type="positiveInteger"/>
            <element name="price" type="string"/>
        </sequence>
    </complexType>
    <simpleType name="Group">
        <restriction base="string">
            <enumeration value="Analgesics"/>
            <enumeration value="Antiviral"/>
            <enumeration value="Tissue regeneration stimulant"/>
        </restriction>
    </simpleType>
    <complexType name="Certificate">
        <sequence>
            <element name="number" type="nonNegativeInteger"/>
            <element name="shelfLife" type="string"/>
            <element name="registeringOrganization" type="string"/>
        </sequence>
    </complexType>
    <simpleType name="shelfLife">
        <restriction base="string">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{6,9}"/>
        </restriction>
    </simpleType>


</schema>

=== dmitry300/DmitryGarist/task08/src/main/resources/data/medicine.xml
<?xml version ="1.0" encoding = "UTF-8"?>

<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.training.by/bean"
           xsi:schemaLocation="http://www.training.by/bean medicine.xsd">
    <medicine id="1">
        <name>Citramon-Borimed</name>
        <pharm>JSC "Borisovskuy plant of medicines" RB</pharm>
        <group>Analgesics</group>
        <analogs>
            <analog>Askofen</analog>
            <analog>Pharmadol</analog>
            <analog>Ibuprofen</analog>
        </analogs>
        <version>Tablet</version>
        <certificate>
            <number>6</number>
            <shelfLife>4 years</shelfLife>
            <registeringOrganization>Ministry of Health of the Republic of Belarus</registeringOrganization>
        </certificate>
        <package>
            <type>Contour cell packaging</type>
            <amount>10</amount>
            <price>0.55 ruble</price>
        </package>
        <dosage>
            <dose>1-2</dose>
            <frequency>4-6 times/day</frequency>
        </dosage>
    </medicine>
    <medicine id="2">
        <name>Angrimax</name>
        <pharm>UE "Minskintercaps" RB</pharm>
        <group>Antiviral</group>
        <analogs>
            <analog>Orvikold</analog>
            <analog>Grippolek</analog>
            <analog>Antigrippin</analog>
        </analogs>
        <version>Capsule</version>
        <certificate>
            <number>20</number>
            <shelfLife>2 years</shelfLife>
            <registeringOrganization>Ministry of Health of the Republic of Belarus</registeringOrganization>
        </certificate>
        <package>
            <type>Contour cell packaging</type>
            <amount>20</amount>
            <price>6.02 ruble</price>
        </package>
        <dosage>
            <dose>2</dose>
            <frequency>4-6 times/day</frequency>
        </dosage>
    </medicine>
    <medicine id="3">
        <name>Bepanten</name>
        <pharm>Bayer Consumer Care AG</pharm>
        <group>Tissue regeneration stimulant</group>
        <analogs>
            <analog>Dexpanthenol</analog>
            <analog>Panthenol</analog>
            <analog>Pantoderm</analog>
        </analogs>
        <version>Salve</version>
        <certificate>
            <number>1</number>
            <shelfLife>3 years</shelfLife>
            <registeringOrganization>Ministry of Health of the Republic of Belarus</registeringOrganization>
        </certificate>
        <package>
            <type>Aluminum tube in carton</type>
            <amount>10</amount>
            <price>18.5 ruble</price>
        </package>
        <dosage>
            <dose>1</dose>
            <frequency>1 times/day</frequency>
        </dosage>
    </medicine>
</medicines>
        <!--
        Лекарственные препараты
        Лекарственные препараты имеют следующие характеристики.
        Name – наименование препарата.
        Pharm – фирма-производитель.
        Group – группа препаратов к которым относится лекарство (антибиотики, болеутоляющие, витамины и т.п.).
        Analogs (может быть несколько) – содержит наименование аналога.
        Versions – варианты исполнения (консистенция/вид: таблетки, капсулы, порошок, капли и т.п.). Для каждого варианта исполнения может быть несколько производителей лекарственных препаратов со следующими характеристиками:
        Certificate – свидетельство о регистрации препарата (номер, даты выдачи/истечения действия, регистрирующая организация);
        Package – упаковка (тип упаковки, количество в упаковке, цена за упаковку);
        Dosage – дозировка препарата, периодичность приема.
        Корневой элемент назвать Medicins.
        -->
